services:
  ray-casting:
    build: .
    container_name: ray-casting
    environment:
      DISPLAY: $DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/$HOME/.Xauthority
    network_mode: host
    user: "1000:1000"
