name: Build with CMake and SDL2

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.0.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-suggests --no-install-recommends cmake libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libomp-dev

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make -j $(nproc)

    - name: Strip debugging symbols
      run: |
        strip build/ray-casting
        strip build/test

    - name: Export test executable
      uses: actions/upload-artifact@v3.1.3
      with:
        name: test
        path: build/test

    - name: Export ray-casting executable
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ray-casting
        path: build/ray-casting

  test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0

      - name: Import test executable
        uses: actions/download-artifact@v2.1.1
        with:
          name: test
          path: test

      - name: Run tests
        run: |
          mkdir build
          build/test
