name: Build with CMake and SDL2

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libomp-dev

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        make -j $(nproc)

    - name: Strip debugging symbols
      run: |
        strip build/ray-casting
        strip build/test

    - name: Export test executable
      uses: actions/upload-artifact@v2
      with:
        name: test
        path: build/test

    - name: Export ray-casting executable
      uses: actions/upload-artifact@v2
      with:
        name: ray-casting
        path: build/ray-casting
