name: Common

on:
  - push

jobs:
  cppcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-suggests --no-install-recommends cppcheck

      - name: Run cppcheck
        run: cppcheck --language=c --std=c99 --enable=all --suppress=missingIncludeSystem \
          --max-ctu-depth=10 --force --error-exitcode=1 .
